# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb0e098c71d968f1a59b918b6dfc0e874907344ae1664325c3a3aeb39a15d7914796f2ccdbec77930fc581d91218221e3ccc9679408942e3e2b20b163235b8a

test:
  secret_key_base: deb21445c68c50c8c75bf23a665a9285d5ded0fbf908c22ed8c4f2c221a1073dccc2747c3a1563dbfb534560422b476d45f5f643dc28dab6681905463a3a1264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
